server {
    listen 80;
    index index.php index.html index.htm;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/public;
    server_name _;

    # Flutter Web Admin
    location /frontend_admin/ {
        alias /var/www/public/frontend_admin;
        try_files $uri $uri/ /frontend_admin/index.html;
        gzip_static on;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Flutter Web User
    location /frontend_user/ {
        alias /var/www/public/frontend_user/;
        try_files $uri $uri/ /frontend_user/index.html;
        gzip_static on;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }


    # Static files and Laravel routing
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    # PHP execution
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Deny access to hidden files
    location ~ /\. {
        deny all;
    }
}
